formatter: "markdown"

recursive:
  enabled: true
  path: modules

content: |-
  # Logs analytics workspace
  
  {{ .Requirements }}
  
  {{ .Providers }}
  
  {{ .Modules }}
  
  {{ .Resources }}
  
  {{ .Inputs }}
  
  {{ .Outputs }}
  
  ## Example
  
  ```hcl
  {{ include "../../examples/log_analytics_workspace.tf" }}
  ```
