formatter: "markdown"

recursive:
  enabled: true
  path: modules

content: |-
  # Private endpoint
  
  {{ .Requirements }}
  
  {{ .Providers }}
  
  {{ .Modules }}
  
  {{ .Resources }}
  
  {{ .Inputs }}
  
  {{ .Outputs }}
  
  ## Example
  
  ```hcl
  {{ include "../../examples/resource_group.tf" }}
  
  {{ include "../../examples/vnet1.tf" }}
  
  {{ include "../../examples/storage_account.tf" }}
  
  {{ include "../../examples/private_endpoint.tf" }}
  ```
